<a href="https://colab.research.google.com/github/Sledger9/TCS-iON-RIO-125/blob/main/GrammaticalErrorDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.preprocessing import MinMaxScaler
print(tf.__version__)
import sys
print(sys.version)
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

%matplotlib inline


2.12.0
3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data = pd.read_csv("/content/drive/MyDrive/Datasets/in_domain_train.csv")
data_dev = pd.read_csv("/content/drive/MyDrive/Datasets/in_domain_dev.csv")
data = data.values
data_dev = data_dev.values
x_train = data[:,1]
y_train = data[:,2]

x_dev = data_dev[:,1]
y_dev = data_dev[:,2]

y = np.concatenate((y_dev,y_train))
x = np.concatenate((x_dev,x_train))
import random
random.shuffle(y)
random.shuffle(x)  
y_t_0 = y[1500:]
y_d_0 = y[:1500]
x_t_0 = x[1500:]
x_d_0 = x[:1500]

In [5]:
f = open('/content/drive/MyDrive/Datasets/entries.train')
lines=f.readlines()
sentences = []
y = []
line = 0
cur = 0
for x in lines:
    cur = cur +1
    if x=='\n' : continue
    else: line=line+1
    if line>=60000: 
        print(x,cur)
        break
    sentences.append(x.split('\t')[4])
    if x.split('\t')[0] == '0':
        y.append(1)
    else:
        y.append(0)
f.close()

0	307365	http://lang-8.com/18840/journals/84655	21	They asked me to explain `` Ionic Bond `` in English .
 65781


In [6]:
print(len(y),len(sentences))

59999 59999


In [7]:
zeros = 0
ones = 0
for l in y:
    if l==0:
        zeros = zeros+1
    else:
        ones = ones+1
print(zeros,ones)

29389 30610


In [8]:
y_t_1 = y[5000:]
y_d_1 = y[:5000]
x_t_1 = sentences[5000:]
x_d_1 = sentences[:5000]

y_t = np.concatenate((y_t_1,y_t_0.tolist()))
y_d = np.concatenate((y_d_1,y_d_0.tolist()))
sentences_t = np.concatenate((x_t_1,x_t_0))
sentences_d = np.concatenate((x_d_1,x_d_0))

print(len(y_t),len(y_d),sentences_t[:3],sentences_d[:3])

62351 6500 ['I really miss them .\n' "I 'm not sure how I spend more 3 weeks here ."
 'Oh my god !\n'] ['Good luck on your new start !\n'
 'My teacher is going to move to change his job .\n'
 'He is a so nice guy and taught me English very kindly and was willing to accept my getting off the track .\n']


In [9]:
embedding_dim = 100
max_length = 120
trunc_type='post'
oov_tok = "<OOV>"

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(oov_token=oov_tok)
tokenizer.fit_on_texts(sentences_t)

vocab_size = len(tokenizer.word_index)+1
sequences = tokenizer.texts_to_sequences(sentences_t)
padded = pad_sequences(sequences,maxlen=max_length)

testing_sequences = tokenizer.texts_to_sequences(sentences_d)
testing_padded = pad_sequences(testing_sequences,maxlen=max_length)

y_train_np = np.array(y_t,np.float32)
y_dev_np = np.array(y_d,np.float32)
testing_padded_np = np.array(testing_padded,np.float32)
padded_np = np.array(padded,np.float32)

y_train_tf = tf.convert_to_tensor(y_train_np, np.float32)
y_dev_tf = tf.convert_to_tensor(y_dev_np, np.float32)
testing_padded_tf = tf.convert_to_tensor(testing_padded_np, np.float32)
padded_tf = tf.convert_to_tensor(padded_np, np.float32)

In [10]:
print(padded_np)

[[0.000e+00 0.000e+00 0.000e+00 ... 9.100e+01 6.920e+02 7.000e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.310e+02 6.310e+02 1.360e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 4.250e+02 7.000e+00 8.420e+02]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 8.399e+03 2.161e+03 7.012e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 4.335e+03 5.230e+03 3.453e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 4.870e+02 4.800e+01 4.734e+03]]


In [12]:
embeddings_index = dict()
f = open('/content/drive/MyDrive/Datasets/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = np.array(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [13]:
count = 0
for word,i in tokenizer.word_index.items():
    cur = cur+1
print(cur)

104401


In [14]:
embedding_matrix = np.zeros((vocab_size, embedding_dim))
for word, i in tokenizer.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [15]:
from tensorflow.keras.layers import LSTM, Dense, Dropout, Masking, Embedding
from tensorflow.keras import regularizers
from tensorflow.keras.layers import BatchNormalization
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, weights=[embedding_matrix], input_length=max_length, trainable=False),
    tf.keras.layers.LSTM(64,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(5, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(loss = 'binary_crossentropy', optimizer=opt,metrics = ['accuracy'])
print(model.summary())
print(y_dev_tf.shape,y_train_tf.shape,padded_tf.shape,testing_padded_tf.shape)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 120, 100)          3862100   
                                                                 
 lstm (LSTM)                 (None, 64)                42240     
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 batch_normalization (BatchN  (None, 64)               256       
 ormalization)                                                   
                                                                 
 dense (Dense)               (None, 5)                 325       
                                                                 
 dense_1 (Dense)             (None, 1)                 6         
                                                        

In [16]:
print(testing_padded_tf.shape,y_dev_tf.shape,padded_tf.shape,y_train_tf.shape)

(6500, 120) (6500,) (62351, 120) (62351,)


In [17]:
num_epochs = 5
model.fit(padded_tf, y_train_tf, epochs=num_epochs, validation_data=(testing_padded_tf, y_dev_tf))

Epoch 1/5
1949/1949 [==============================] - 443s 224ms/step - loss: 0.6532 - accuracy: 0.6218 - val_loss: 0.6145 - val_accuracy: 0.6682
Epoch 2/5
1949/1949 [==============================] - 428s 220ms/step - loss: 0.6255 - accuracy: 0.6443 - val_loss: 0.6136 - val_accuracy: 0.6668
Epoch 3/5
1949/1949 [==============================] - 423s 217ms/step - loss: 0.6202 - accuracy: 0.6491 - val_loss: 0.6093 - val_accuracy: 0.6671
Epoch 4/5
1949/1949 [==============================] - 419s 215ms/step - loss: 0.6193 - accuracy: 0.6507 - val_loss: 0.6065 - val_accuracy: 0.6698
Epoch 5/5
1949/1949 [==============================] - 416s 213ms/step - loss: 0.6162 - accuracy: 0.6533 - val_loss: 0.6071 - val_accuracy: 0.6718


In [18]:
custom = input("Sentence: ")
custom_test_1 = np.array([custom])
custom_1 = tokenizer.texts_to_sequences(custom_test_1)
flag = 0
for q in custom_1[0]:
    if q!=1: 
        flag = 1
        break
if flag == 0: 
    print("All words out of vocabulary!")
custom_2 = pad_sequences(custom_1,maxlen=max_length)
custom_np = np.array(custom_2,np.float32)
custom_tf = tf.convert_to_tensor(custom_np,np.float32)
prob = model.predict(custom_tf)
if prob<0.65:
    print("Grammatically \033[1m INCORRECT \033[0m with probability: ",1-prob)
else:
    print("Grammatically \033[1m CORRECT \033[0m with probability: ",prob)
print(prob)
print(custom_test_1)

Sentence: I have reading the book
1/1 [==============================] - 0s 206ms/step
Grammatically  INCORRECT  with probability:  [[0.40681046]]
[[0.59318954]]
['I have reading the book']
